CREATE TABLE alumnos (
    id BIGSERIAL PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    dni VARCHAR(20) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    nacionalidad VARCHAR(50) NOT NULL,
    fecha_nacimiento DATE NOT NULL,
    carrera VARCHAR(100) NOT NULL,
    domicilio VARCHAR(300) NOT NULL,
    codigo_postal VARCHAR(20) NOT NULL,
    localidad VARCHAR(100) NOT NULL,
    provincia VARCHAR(100) NOT NULL,
    /*CIUDAD EN LA CUAL VIVE SU NUCLEO FAMILIAR*/
    ciudad_familia VARCHAR(100) NOT NULL,
    /*REFERENCIA A LA VIVIENDA EN LA QUE ESTA EL ESTUDIANTE*/
    vivienda VARCHAR(200) NOT NULL,
    /*CONDICION LABORAL DEL ESTUDIANTE*/
    condicion_laboral VARCHAR(200) NOT NULL,
    /*SALUD DEL ESTUDIANTE*/
    salud VARCHAR(200) NOT NULL,
    tiene_discapacidad BOOLEAN NOT NULL,
    discapacidad_detalle VARCHAR(300),
    /*ESTADO ACADEMICO DEL ESTUDIANTE*/
    estado_academico VARCHAR(200) NOT NULL
);

CREATE TABLE becas (
    id BIGSERIAL PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(150) NOT NULL,
    descripcion TEXT NOT NULL,
    /*TIPO DE BECA (BASE-BIS)*/
    tipo_beca VARCHAR(20) NOT NULL,
    /*CASO DE SER UNA BECA BIS REQUERIRA QUE EL ESTUDIANTE ESTE CURSANDO UNA INGENIERIA*/
    requiere_ingenieria BOOLEAN NOT NULL
);

CREATE TABLE familiares (
    id BIGSERIAL PRIMARY KEY AUTO_INCREMENT,
    /*CAMPO EL CUAL GUARDA LA REFERENCIA CON EL ALUMNO*/
    alumno_id BIGSERIAL NOT NULL,
    nombre VARCHAR (100) NOT NULL,
    apellido VARCHAR (100) NOT NULL,
    dni VARCHAR(20) UNIQUE NOT NULL,
    parentesco_alumno VARCHAR(50) NOT NULL,
    ocupacion VARCHAR(300) NOT NULL,
    ingreso DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (alumno_id) REFERENCES alumnos(id)
);